/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:15:12 GMT-0400 (Eastern Daylight Time)

enum EAuthSessionGuardType {
	Unknown = 0,
	None = 1,
	EmailCode = 2,
	DeviceCode = 3,
	DeviceConfirmation = 4,
	EmailConfirmation = 5,
	MachineToken = 6,
	LegacyMachineAuth = 7
}

export default EAuthSessionGuardType;
