/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:15:12 GMT-0400 (Eastern Daylight Time)

enum EAuthTokenRevokeAction {
	Logout = 0,
	Permanent = 1,
	Replaced = 2,
	Support = 3,
	Consume = 4,
	NonRememberedLogout = 5,
	NonRememberedPermanent = 6,
	Automatic = 7
}

export default EAuthTokenRevokeAction;
