/* eslint-disable */
// Auto-generated by generate-enums script on Tue Aug 30 2022 02:49:14 GMT-0400 (Eastern Daylight Time)

enum EAuthTokenPlatformType {
	Unknown = 0,
	SteamClient = 1,
	WebBrowser = 2,
	MobileApp = 3
}

export default EAuthTokenPlatformType;
