/* eslint-disable */
// Auto-generated by generate-enums script on Thu Mar 02 2023 22:18:52 GMT-0500 (Eastern Standard Time)

enum EAuthSessionGuardType {
	Unknown = 0,
	None = 1,
	EmailCode = 2,
	DeviceCode = 3,
	DeviceConfirmation = 4,
	EmailConfirmation = 5,
	MachineToken = 6
}

export default EAuthSessionGuardType;
