/* eslint-disable */
// Auto-generated by generate-enums script on Tue Aug 30 2022 02:49:14 GMT-0400 (Eastern Daylight Time)

enum EAuthTokenState {
	Invalid = 0,
	New = 1,
	Confirmed = 2,
	Issued = 3,
	Denied = 4,
	LoggedOut = 5,
	Revoked = 99
}

export default EAuthTokenState;
