/* eslint-disable */
// Auto-generated by generate-enums script on Tue Aug 30 2022 02:49:14 GMT-0400 (Eastern Daylight Time)

enum EAuthSessionGuardType {
	Unknown = 0,
	None = 1,
	EmailCode = 2,
	DeviceCode = 3,
	DeviceConfirmation = 4,
	EmailConfirmation = 5,
	MachineToken = 6
}

export default EAuthSessionGuardType;
