/* eslint-disable */
// Auto-generated by generate-enums script on Mon Oct 17 2022 00:56:09 GMT-0400 (Eastern Daylight Time)

enum EAuthTokenRevokeAction {
	Logout = 0,
	Permanent = 1,
	Replaced = 2,
	Support = 3
}

export default EAuthTokenRevokeAction;
