/* eslint-disable */
// Auto-generated by generate-enums script on Thu Mar 02 2023 22:18:52 GMT-0500 (Eastern Standard Time)

enum EAuthTokenRevokeAction {
	Logout = 0,
	Permanent = 1,
	Replaced = 2,
	Support = 3
}

export default EAuthTokenRevokeAction;
