/* eslint-disable */
// Auto-generated by generate-enums script on Thu Mar 02 2023 22:18:52 GMT-0500 (Eastern Standard Time)

enum EBanContentCheckResult {
	NotScanned = 0,
	Reset = 1,
	NeedsChecking = 2,
	VeryUnlikely = 5,
	Unlikely = 30,
	Possible = 50,
	Likely = 75,
	VeryLikely = 100
}

export default EBanContentCheckResult;
