/* eslint-disable */
// Auto-generated by generate-enums script on Tue Aug 30 2022 02:49:14 GMT-0400 (Eastern Daylight Time)

enum EBanContentCheckResult {
	NotScanned = 0,
	Reset = 1,
	NeedsChecking = 2,
	VeryUnlikely = 5,
	Unlikely = 30,
	Possible = 50,
	Likely = 75,
	VeryLikely = 100
}

export default EBanContentCheckResult;
