/* eslint-disable */
// Auto-generated by generate-enums script on Thu Mar 02 2023 22:18:52 GMT-0500 (Eastern Standard Time)

enum ESessionPersistence {
	Invalid = -1,
	Ephemeral = 0,
	Persistent = 1
}

export default ESessionPersistence;
