/* eslint-disable */
// Auto-generated by generate-enums script on Tue Aug 30 2022 02:49:14 GMT-0400 (Eastern Daylight Time)

enum ESessionPersistence {
	Invalid = -1,
	Ephemeral = 0,
	Persistent = 1
}

export default ESessionPersistence;
