/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:15:12 GMT-0400 (Eastern Daylight Time)

enum ETokenRenewalType {
	None = 0,
	Allow = 1
}

export default ETokenRenewalType;
